spring:
  application:
    name: DistributeLock
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    initialization-mode: always
    url: ${DB_URL}
    username: ${DB_UNAME}
    password: ${DB_UPASS}
    driver-class-name: ${DB_DRIVER}
  flyway:
    baseline-on-migrate: true
    clean-on-validation-error: false
service:
  key: demo-svc
  threads: 20
logging:
  file:
    name: /var/log/distribute-lock.log