# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: upassword
      MYSQL_DATABASE: distribute-lock-local
      TZ: Asia/Shanghai
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080